image: registry.xxx.com/lain/python:2.7.14


job:reinstall: &job
    only:
        - schedules
    tags:
        - docker
    before_script:
        - pip install pip
        - pip install -U pipenv
        - pipenv install --deploy
    script:
        - pipenv run python generate.py $GITLAB_USER_EMAIL $DNS_TOKEN $CDN_ACCESS_ID $CDN_ACCESS_SECRET run.sh
        - pipenv run bash run.sh

job:manual:
    <<: *job
    only:
        - master
    when: manual
